---
title: "learndplyr"
author: "Samuel"
date: "4/24/2020"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
confirmed_w <- read.csv("data_input/confirmed_global.csv")
tail(confirmed_w)
```

```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  gather(key="date", value="Value", -Country.Region)
```


```{r}
pivot_longer(confirmed_w[,c(2, 5:ncol(confirmed_w))], -Country.Region)
```


```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-Country.Region, names_to = "date", values_to = "value") %>% 
  head(4)
```

```{r}
library(ggplot2)
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-Country.Region, names_to = "date", values_to = "value") %>% 
  head(300) %>% 
  ggplot(aes(x=value)) + geom_histogram()
```
```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-Country.Region, names_to = "date", values_to = "Value") %>% 
  dim()
```

```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-"Country.Region", names_to = "date", values_to = "Value") %>% 
  group_by(Country.Region, date) %>% 
  summarise("Value"=sum(Value)) %>% 
  dim()
```

```{r}
confirmed_w %>%
  select(-Lat, -Long) %>% 
  pivot_longer(-c(Country.Region, Province.State), names_to = "date", values_to = "Value") %>% 
  filter(Country.Region %in% c('Australia', 'Canada') & date == 'X4.10.20') %>% 
  head(10)
```

```{r}
confirmed_w %>%
  select(-Lat, -Long) %>% 
  pivot_longer(-c(Country.Region, Province.State), names_to = "date", values_to = "Value") %>% 
  filter(Country.Region %in% c('Australia', 'Canada') & date == 'X4.10.20') %>% 
  group_by(Country.Region) %>% 
  summarise("Avg"=mean(Value), "Sum"=sum(Value)) %>% 
  ungroup()
```

```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-"Country.Region", names_to = "date", values_to = "Value") %>% 
  group_by(Country.Region, date) %>% 
  summarise("Value"=sum(Value)) %>% 
  ungroup() %>% 
  str()
```

```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-"Country.Region", names_to = "date", values_to = "Value") %>% 
  group_by(Country.Region, date) %>% 
  summarise("Value"=sum(Value)) %>% 
  ungroup() %>% 
  select(date, "country"=Country.Region, Value) %>% 
  mutate(country=as.character(country), "Exp"=log(Value))
```

```{r}
d1 <- "X3.9.20"
substring(d1, 2, nchar(d1))
```

```{r}
nchar(d1)
```



```{r}
as.Date(substring(d1, 2, nchar(d1)), format="%m.%d.%y")
```


```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-"Country.Region", names_to = "date", values_to = "Value") %>% 
  group_by(Country.Region, date) %>% 
  summarise("Value"=sum(Value)) %>% 
  ungroup() %>% 
  select(date, "country"=Country.Region, Value)
```

```{r}
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-"Country.Region", names_to = "date", values_to = "Value") %>% 
  group_by(Country.Region, date) %>% 
  summarise("Value"=sum(Value)) %>% 
  ungroup() %>% 
  select(date, "country"=Country.Region, Value) %>% 
  mutate(date=as.Date(substring(date, 2, nchar(date)),"%m.%d.%y")) %>% 
  arrange(-Value)
```


```{r}
cleaned_confirmed <- confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-"Country.Region", names_to = "date", values_to = "Value") %>% 
  group_by(Country.Region, date) %>% 
  summarise("Value"=sum(Value)) %>% 
  ungroup() %>% 
  select(date, "country"=Country.Region, Value) %>% 
  mutate(date=as.Date(substring(date, 2, nchar(date)),"%m.%d.%y")) %>% 
  arrange(date)
```

## Structuring your R Scripts
This is the end of the dplyr lesson.
The following section is for the "Structuring your R scripts" lesson. 

```{r}
peek <- function(data){
  rbind(head(data,2), 
        tail(data,2))
}
```

```{r}
source("preprocess.R")
confirmed_w <- read.csv("data_input/confirmed_global.csv")
peek(confirmed_w)
```

```{r}
library(dplyr)
library(tidyr)
confirmed_w %>%
  select(-Province.State, -Lat, -Long) %>% 
  pivot_longer(-Country.Region, names_to = "date", values_to = "value") %>% 
  peek()
```

```{r}
peek(mtcars)
```


